/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Charts: typeof import('./src/components/Statistics/Charts.vue')['default']
    EndFormItem: typeof import('./src/components/Item/EndFormItem.vue')['default']
    InputPad: typeof import('./src/components/Item/InputPad.vue')['default']
    ItemCreate: typeof import('./src/components/Item/ItemCreate.vue')['default']
    ItemList: typeof import('./src/components/Item/ItemList.vue')['default']
    ItemSummary: typeof import('./src/components/Item/ItemSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartFormItem: typeof import('./src/components/Item/StartFormItem.vue')['default']
    TagCreate: typeof import('./src/components/Tag/TagCreate.vue')['default']
    TagEdit: typeof import('./src/components/Tag/TagEdit.vue')['default']
    TagForm: typeof import('./src/components/Tag/TagForm.vue')['default']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    WelcomeFourAction: typeof import('./src/components/welcome/WelcomeAction/WelcomeFourAction.vue')['default']
    WelcomeFourCard: typeof import('./src/components/welcome/WelcomeCard/WelcomeFourCard.vue')['default']
    WelcomeOneAction: typeof import('./src/components/welcome/WelcomeAction/WelcomeOneAction.vue')['default']
    WelcomeOneCard: typeof import('./src/components/welcome/WelcomeCard/WelcomeOneCard.vue')['default']
    WelcomeThreeAction: typeof import('./src/components/welcome/WelcomeAction/WelcomeThreeAction.vue')['default']
    WelcomeThreeCard: typeof import('./src/components/welcome/WelcomeCard/WelcomeThreeCard.vue')['default']
    WelcomeTwoAction: typeof import('./src/components/welcome/WelcomeAction/WelcomeTwoAction.vue')['default']
    WelcomeTwoCard: typeof import('./src/components/welcome/WelcomeCard/WelcomeTwoCard.vue')['default']
  }
}
